version: '3.8'

services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dockerDB
      - POSTGRES_PASSWORD=1234
    volumes:
      - "db-data:/var/lib/postgresql/data"


  app:
    build:
      context: services/app
      dockerfile: Dockerfile
    command: java -jar ./app.jar
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/dockerDB
      - JS_URL=http://localhost
    image: 'my-java-application'
    ports:
      - 8091:8091
    depends_on:
      - postgres

volumes:
    db-data:

